In [40]:
import numpy as np
import pandas as pd
import matplotlib as mlt

In [41]:
df = pd.read_csv("Housing.csv")
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [42]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [43]:
df.isnull().sum

<bound method DataFrame.sum of      price   area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    False  False     False      False    False     False      False
1    False  False     False      False    False     False      False
2    False  False     False      False    False     False      False
3    False  False     False      False    False     False      False
4    False  False     False      False    False     False      False
..     ...    ...       ...        ...      ...       ...        ...
540  False  False     False      False    False     False      False
541  False  False     False      False    False     False      False
542  False  False     False      False    False     False      False
543  False  False     False      False    False     False      False
544  False  False     False      False    False     False      False

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0       False            False            False    False     False
1       False            False            False    False     False
2       False            False            False    False     False
3       False            False            False    False     False
4       False            False            False    False     False
..        ...              ...              ...      ...       ...
540     False            False            False    False     False
541     False            False            False    False     False
542     False            False            False    False     False
543     False            False            False    False     False
544     False            False            False    False     False

     furnishingstatus
0               False
1               False
2               False
3               False
4               False
..                ...
540             False
541             False
542             False
543             False
544             False

[545 rows x 13 columns]>

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [45]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [46]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [48]:
model = LinearRegression()

In [68]:
x= df.drop(['price', 'mainroad', 'guestroom', 'basement','hotwaterheating','airconditioning','prefarea','furnishingstatus' ], axis=1)
y = df['price']

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=80)

In [51]:
x_train.shape

(436, 12)

In [71]:
y_train.shape

(436,)

In [72]:
x_test.shape

(109, 5)

In [73]:
y_test.shape

(109,)

In [74]:
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [76]:
from sklearn.metrics import mean_absolute_error, r2_score
print("MAE", mean_absolute_error(y_test, y_pred))
print("r2 Score",r2_score(y_test, y_pred))

MAE 1044725.5035962691
r2 Score 0.5410144971501163

In [77]:
import pickle
pickle.dump(model,open('house_price_model.pkl','wb'))